### PR TITLE
Use new Promise() syntax instead of Promise.resolve().

### PR DESCRIPTION
**Pull request by hulkish**
I could be mistaken, but my findings suggest this is slightly less overhead.

### CODE REVIEW

**Comment by ljharb** [comment]
It's not less overhead, but it does violate the spec. The requiring needs to happen on the next tick; new Promise makes it happen synchronously.

**Comment by hulkish** [comment]
@ljharb That makes sense, didn't occur to me. So, you're saying that the `Promise.resolve().then()` was intentional to enforce the require to occur on next tick?

**Comment by ljharb** [comment]
Precisely. See 1fdf421c05c1140f6d71444ea2b27638

**Comment by hulkish** [comment]
cool beans, nothing to see here folks ➡️ move along ➡️

**Pull request closed without merging**
